### ISSUE TITLE
Support TAP

### ISSUE THREAD

**Issue by sindresorhus** [AERO-ff/qunit#5]
https://testanything.org

Through a `--tap` flag.

Would enable users to use any TAP reporter.

Spec: https://testanything.org/tap-version-13-specification.html
## 

http://testanything.org/testing-with-tap/c-plus-plus.html
https://github.com/zorgnax/libtap

**Comment by Qix-** [comment]
Cool, definitely will look into this. :+1: Shouldn't be too difficult.

**Comment by Qix-** [comment]
Landed **basic** support in a39b1c26eeba65ee4bf2ea82667911fe2e0fcf94. I'll add more support if better consumers come out or if people actually start using this :dancer: 

To enable TAP output, `#define QUNIT_TAP` (or on the command line) before `#include "quint.h"`.
